---
ceos1:
    nornir_host: 127.0.0.1
    nornir_network_api_port: 443
    groups: ['ceos_lab']

ceos2:
    nornir_host: 127.0.0.1
    transport: https
    nornir_network_api_port: 8443
    groups: ['ceos_lab']
